CREATE DATABASE yeticave
  DEFAULT CHARACTER SET utf8
  DEFAULT COLLATE utf8_general_ci;

USE yeticave;

CREATE TABLE category (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  name CHAR NOT NULL,
  class CHAR
);

CREATE TABLE lot (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  name CHAR NOT NULL,
  description TEXT,
  img_path CHAR,
  start_price INT NOT NULL,
  finish_date DATETIME NOT NULL,
  bid_step INT NOT NULL,
  user_id INT NOT NULL,
  category_id INT NOT NULL,

  FOREIGN KEY (user_id)  REFERENCES users (id) ON UPDATE CASCADE ON DELETE RESTRICT,
  FOREIGN KEY (category_id)  REFERENCES category (id) ON UPDATE CASCADE ON DELETE RESTRICT
);


CREATE TABLE bid (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  bid INT,
  user_id INT NOT NULL,
  lot_id INT NOT NULL,

  FOREIGN KEY (user_id)  REFERENCES users (id) ON UPDATE CASCADE ON DELETE RESTRICT,
  FOREIGN KEY (lot_id)  REFERENCES lot (id) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE users (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  email CHAR NOT NULL UNIQUE,
  username  CHAR NOT NULL UNIQUE,
  password CHAR NOT NULL,
  contacts TEXT,
  create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  lot_id INT NOT NULL,
  bid_id INT NOT NULL,

  FOREIGN KEY (lot_id)  REFERENCES lot (id) ON UPDATE CASCADE ON DELETE RESTRICT,
  FOREIGN KEY (bid_id)  REFERENCES bid (id) ON UPDATE CASCADE ON DELETE RESTRICT
);
